# Generated by Django 5.0.6 on 2024-07-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Parties", "0002_alter_party_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="logo",
            field=models.ImageField(default="default.jpeg", upload_to="party_logos"),
        ),
    ]
