# Generated by Django 5.0.6 on 2024-07-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Parties", "0004_alter_party_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="logo",
            field=models.ImageField(
                default="default.jpeg",
                max_length=255,
                upload_to="Election\\media\\party_logos",
            ),
        ),
    ]
