# Generated by Django 5.0.6 on 2024-07-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Parties", "0005_alter_party_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="logo",
            field=models.ImageField(
                default="default.jpeg", max_length=255, upload_to="party_logos"
            ),
        ),
    ]
